const Foods = [
  {
    id: 1,
    name: "Healthy Meal Plan",
    price: 23.99,
    category: "lunch",
    shortDesc: "How we dream about future",
    desc: "It provides energy and nutrients to keep the body and brain working through the afternoon. According to experts, lunch provides nourishment to the body and brain and reduces stress and eating lunch provides a break from the activities of the day and gives energy for the rest of the afternoon.",
    thumbnail: "https://i.ibb.co/G9Rt0Yx/lunch6.png",
    images: [
      "https://i.ibb.co/G9Rt0Yx/lunch6.png",
      "https://i.ibb.co/F5T3Hrc/lunch5.png",
      "https://i.ibb.co/nbR114c/lunch4.png",
    ],
  },
  {
    id: 2,
    name: "Fried Chicken",
    price: 9.99,
    category: "lunch",
    shortDesc: "How we dream about future",
    desc: "It provides energy and nutrients to keep the body and brain working through the afternoon. According to experts, lunch provides nourishment to the body and brain and reduces stress and eating lunch provides a break from the activities of the day and gives energy for the rest of the afternoon.",
    thumbnail: "https://i.ibb.co/F5T3Hrc/lunch5.png",
    images: [
      "https://i.ibb.co/G9Rt0Yx/lunch6.png",
      "https://i.ibb.co/F5T3Hrc/lunch5.png",
      "https://i.ibb.co/nbR114c/lunch4.png",
    ],
  },
  {
    id: 3,
    name: "Tarragon-Rubbed Salmon",
    price: 6.99,
    category: "lunch",
    shortDesc: "How we dream about future",
    desc: "It provides energy and nutrients to keep the body and brain working through the afternoon. According to experts, lunch provides nourishment to the body and brain and reduces stress and eating lunch provides a break from the activities of the day and gives energy for the rest of the afternoon. ",
    thumbnail: "https://i.ibb.co/nbR114c/lunch4.png",
    images: [
      "https://i.ibb.co/G9Rt0Yx/lunch6.png",
      "https://i.ibb.co/F5T3Hrc/lunch5.png",
      "https://i.ibb.co/nbR114c/lunch4.png",
    ],
  },
  {
    id: 4,
    name: "Indian Lunch",
    price: 8.99,
    category: "lunch",
    shortDesc: "How we dream about future",
    desc: "It provides energy and nutrients to keep the body and brain working through the afternoon. According to experts, lunch provides nourishment to the body and brain and reduces stress and eating lunch provides a break from the activities of the day and gives energy for the rest of the afternoon. ",
    thumbnail: "https://i.ibb.co/M21tqfY/lunch3.png",
    images: [
      "https://i.ibb.co/G9Rt0Yx/lunch6.png",
      "https://i.ibb.co/F5T3Hrc/lunch5.png",
      "https://i.ibb.co/nbR114c/lunch4.png",
    ],
  },
  {
    id: 5,
    name: "Korean Lunch with Bread",
    price: 11.99,
    category: "lunch",
    shortDesc: "How we dream about future",
    desc: "It provides energy and nutrients to keep the body and brain working through the afternoon. According to experts, lunch provides nourishment to the body and brain and reduces stress and eating lunch provides a break from the activities of the day and gives energy for the rest of the afternoon. ",
    thumbnail: "https://i.ibb.co/xMBZ4Wz/lunch1.png",
    images: [
      "https://i.ibb.co/G9Rt0Yx/lunch6.png",
      "https://i.ibb.co/F5T3Hrc/lunch5.png",
      "https://i.ibb.co/nbR114c/lunch4.png",
    ],
  },
  {
    id: 6,
    name: "Beaf Steak",
    price: 13.99,
    category: "lunch",
    shortDesc: "How we dream about future",
    desc: "It provides energy and nutrients to keep the body and brain working through the afternoon. According to experts, lunch provides nourishment to the body and brain and reduces stress and eating lunch provides a break from the activities of the day and gives energy for the rest of the afternoon. ",
    thumbnail: "https://i.ibb.co/r4BHdTv/lunch2.png",
    images: [
      "https://i.ibb.co/G9Rt0Yx/lunch6.png",
      "https://i.ibb.co/F5T3Hrc/lunch5.png",
      "https://i.ibb.co/nbR114c/lunch4.png",
    ],
  },
  {
    id: 7,
    name: "Bagel and cream cheese",
    price: 6.99,
    category: "breakfast",
    shortDesc: "How we dream about future",
    desc: "It provides energy and nutrients to keep the body and brain working through the afternoon. According to experts, lunch provides nourishment to the body and brain and reduces stress and eating lunch provides a break from the activities of the day and gives energy for the rest of the afternoon. ",
    thumbnail: "https://i.ibb.co/41bFrRn/breakfast6.png",
    images: [
      "https://i.ibb.co/WWy9jKw/breakfast5.png",
      "https://i.ibb.co/6HPQcxM/breakfast2.png",
      "https://i.ibb.co/JH4MjQn/breakfast4.png",
    ],
  },
  {
    id: 8,
    name: "Breakfast Sandwich",
    price: 9.99,
    category: "breakfast",
    shortDesc: "How we dream about future",
    desc: "It provides energy and nutrients to keep the body and brain working through the afternoon. According to experts, lunch provides nourishment to the body and brain and reduces stress and eating lunch provides a break from the activities of the day and gives energy for the rest of the afternoon. ",
    thumbnail: "https://i.ibb.co/WWy9jKw/breakfast5.png",
    images: [
      "https://i.ibb.co/WWy9jKw/breakfast5.png",
      "https://i.ibb.co/6HPQcxM/breakfast2.png",
      "https://i.ibb.co/JH4MjQn/breakfast4.png",
    ],
  },
  {
    id: 9,
    name: "Eggs Benedict",
    price: 6.99,
    category: "breakfast",
    shortDesc: "How we dream about future",
    desc: "It provides energy and nutrients to keep the body and brain working through the afternoon. According to experts, lunch provides nourishment to the body and brain and reduces stress and eating lunch provides a break from the activities of the day and gives energy for the rest of the afternoon. ",
    thumbnail: "https://i.ibb.co/JH4MjQn/breakfast4.png",
    images: [
      "https://i.ibb.co/WWy9jKw/breakfast5.png",
      "https://i.ibb.co/6HPQcxM/breakfast2.png",
      "https://i.ibb.co/JH4MjQn/breakfast4.png",
    ],
  },
  {
    id: 10,
    name: "Toast croissant Fried Egg",
    price: 5.99,
    category: "breakfast",
    shortDesc: "How we dream about future",
    desc: "It provides energy and nutrients to keep the body and brain working through the afternoon. According to experts, lunch provides nourishment to the body and brain and reduces stress and eating lunch provides a break from the activities of the day and gives energy for the rest of the afternoon. ",
    thumbnail: "https://i.ibb.co/RvcN0Qx/breakfast3.png",
    images: [
      "https://i.ibb.co/WWy9jKw/breakfast5.png",
      "https://i.ibb.co/6HPQcxM/breakfast2.png",
      "https://i.ibb.co/RvcN0Qx/breakfast3.png",
    ],
  },
  {
    id: 11,
    name: "Baked Chicken",
    price: 18.99,
    category: "breakfast",
    shortDesc: "How we dream about future",
    desc: "It provides energy and nutrients to keep the body and brain working through the afternoon. According to experts, lunch provides nourishment to the body and brain and reduces stress and eating lunch provides a break from the activities of the day and gives energy for the rest of the afternoon. ",
    thumbnail: "https://i.ibb.co/6HPQcxM/breakfast2.png",
    images: [
      "https://i.ibb.co/WWy9jKw/breakfast5.png",
      "https://i.ibb.co/6HPQcxM/breakfast2.png",
      "https://i.ibb.co/RvcN0Qx/breakfast3.png",
    ],
  },
  {
    id: 12,
    name: "Fried Egg Toast Brunch",
    price: 11.99,
    category: "breakfast",
    shortDesc: "How we dream about future",
    desc: "It provides energy and nutrients to keep the body and brain working through the afternoon. According to experts, lunch provides nourishment to the body and brain and reduces stress and eating lunch provides a break from the activities of the day and gives energy for the rest of the afternoon. ",
    thumbnail: "https://i.ibb.co/phXs4sD/breakfast1.png",
    images: [
      "https://i.ibb.co/WWy9jKw/breakfast5.png",
      "https://i.ibb.co/6HPQcxM/breakfast2.png",
      "https://i.ibb.co/RvcN0Qx/breakfast3.png",
    ],
  },
  {
    id: 13,
    name: "Salmon with Grapefruit And Salad",
    price: 11.99,
    category: "dinner",
    shortDesc: "How we dream about future",
    desc: "It provides energy and nutrients to keep the body and brain working through the afternoon. According to experts, lunch provides nourishment to the body and brain and reduces stress and eating lunch provides a break from the activities of the day and gives energy for the rest of the afternoon. ",
    thumbnail: "https://i.ibb.co/wgH4y99/dinner6.png",
    images: [
      "https://i.ibb.co/k5BRH1H/dinner5.png",
      "https://i.ibb.co/kX8g1JL/dinner4.png",
      "https://i.ibb.co/d28hhGg/dinner3.png",
    ],
  },
  {
    id: 14,
    name: "Lemony Salmon Piccata",
    price: 21.99,
    category: "dinner",
    shortDesc: "How we dream about future",
    desc: "It provides energy and nutrients to keep the body and brain working through the afternoon. According to experts, lunch provides nourishment to the body and brain and reduces stress and eating lunch provides a break from the activities of the day and gives energy for the rest of the afternoon. ",
    thumbnail: "https://i.ibb.co/k5BRH1H/dinner5.png",
    images: [
      "https://i.ibb.co/k5BRH1H/dinner5.png",
      "https://i.ibb.co/kX8g1JL/dinner4.png",
      "https://i.ibb.co/d28hhGg/dinner3.png",
    ],
  },
  {
    id: 15,
    name: "French fries With cheese",
    price: 13.99,
    category: "dinner",
    shortDesc: "How we dream about future",
    desc: "It provides energy and nutrients to keep the body and brain working through the afternoon. According to experts, lunch provides nourishment to the body and brain and reduces stress and eating lunch provides a break from the activities of the day and gives energy for the rest of the afternoon. ",
    thumbnail: "https://i.ibb.co/kX8g1JL/dinner4.png",
    images: [
      "https://i.ibb.co/k5BRH1H/dinner5.png",
      "https://i.ibb.co/kX8g1JL/dinner4.png",
      "https://i.ibb.co/d28hhGg/dinner3.png",
    ],
  },
  {
    id: 16,
    name: "Garlic Butter Baked Salmon",
    price: 9.99,
    category: "dinner",
    shortDesc: "How we dream about future",
    desc: "It provides energy and nutrients to keep the body and brain working through the afternoon. According to experts, lunch provides nourishment to the body and brain and reduces stress and eating lunch provides a break from the activities of the day and gives energy for the rest of the afternoon. ",
    thumbnail: "https://i.ibb.co/d28hhGg/dinner3.png",
    images: [
      "https://i.ibb.co/k5BRH1H/dinner5.png",
      "https://i.ibb.co/kX8g1JL/dinner4.png",
      "https://i.ibb.co/d28hhGg/dinner3.png",
    ],
  },
  {
    id: 17,
    name: "Tenderloin With Quinoa Pilaf",
    price: 6.99,
    category: "dinner",
    shortDesc: "How we dream about future",
    desc: "It provides energy and nutrients to keep the body and brain working through the afternoon. According to experts, lunch provides nourishment to the body and brain and reduces stress and eating lunch provides a break from the activities of the day and gives energy for the rest of the afternoon. ",
    thumbnail: "https://i.ibb.co/VLLtVw0/dinner1.png",
    images: [
      "https://i.ibb.co/y01qLwP/dinner2.png",
      "https://i.ibb.co/kX8g1JL/dinner4.png",
      "https://i.ibb.co/d28hhGg/dinner3.png",
    ],
  },
  {
    id: 18,
    name: "Spices Chicken Soup",
    price: 9.99,
    category: "dinner",
    shortDesc: "How we dream about future",
    desc: "It provides energy and nutrients to keep the body and brain working through the afternoon. According to experts, lunch provides nourishment to the body and brain and reduces stress and eating lunch provides a break from the activities of the day and gives energy for the rest of the afternoon. ",
    thumbnail: "https://i.ibb.co/y01qLwP/dinner2.png",
    images: [
      "https://i.ibb.co/y01qLwP/dinner2.png",
      "https://i.ibb.co/kX8g1JL/dinner4.png",
      "https://i.ibb.co/d28hhGg/dinner3.png",
    ],
  },
];

const infoData = [
  {
    id: 101,
    name: "Fast Delevery",
    desc: "which turned in a time nearly five minutes faster than the rest of the competition: 35 minutes, 31 seconds. Postmates came in second at 40 minutes, 12 seconds. DoorDash had an average delivery time of 42 minutes, 1 second.",
    img: "https://i.ibb.co/jM8N4Td/adult-blur-blurred-background-687824.png",
    icon: "https://i.ibb.co/mb4Nmzc/Group-204.png",
  },
  {
    id: 256,
    name: "A Good Auto Responder",
    desc: "which turned in a time nearly five minutes faster than the rest of the competition: 35 minutes, 31 seconds. Postmates came in second at 40 minutes, 12 seconds. DoorDash had an average delivery time of 42 minutes, 1 second.",
    img: "https://i.ibb.co/X4YTgm4/chef-cook-food-33614.png",
    icon: "https://i.ibb.co/GJD8gFc/Group-1133.png",
  },
  {
    id: 456,
    name: "Home Delivery",
    desc: "which turned in a time nearly five minutes faster than the rest of the competition: 35 minutes, 31 seconds. Postmates came in second at 40 minutes, 12 seconds. DoorDash had an average delivery time of 42 minutes, 1 second.",
    img: "https://i.ibb.co/3sDFgjB/architecture-building-city-2047397.png",
    icon: "https://i.ibb.co/LJqx2w2/Group-245.png",
  },
];
